spring:
  datasource:
    url: jdbc:mysql://localhost:3306/excel?serverTimezone=UTC&characterEncoding=UTF-8&
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB