spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
      auto-index-creation: true   # ddl-auto
      authentication-database: admin
  profiles:
    active: local