spring:
  datasource:
    username: arn:aws:iam::537331658860:user/jhhong0509
    url: jdbc-secretsmanager:mysql://host:port/dbname
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver