spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql

jwt:
  secretKey: ${SECRET}
  accessExp: ${ACCESS_EXP}
  refreshExp: ${REFRESH_EXP}